version: "3.9"

services:
    database:
        container_name: postgres
        image: postgres
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5433:5432"
        volumes:
            - ./data/db:/var/lib/postgresql/data

    web:
        container_name: herecomesthesun
        build: ./apollo_tms/
        command: python code/manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        volumes:
            - ./apollo_tms:/code
        ports:
            - "8000:8000"
        depends_on:
            - database

    frontend:
        container_name: anotheronebitesthedust
        build: ./taskmanagment/
        command: npm run dev
        volumes:
            - ./taskmanagment:/code
        working_dir: /code
        ports:
            - "8080:5173"
        depends_on:
            - web