# Generated by Django 4.2.1 on 2023-05-30 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='recurrenttask',
            name='start_date',
        ),
        migrations.AddField(
            model_name='task',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.collection'),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date.today()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
