# Generated by Django 4.2.1 on 2023-05-31 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_collection_deletable_alter_task_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.collection'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
