# Generated by Django 4.2.1 on 2023-05-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrenttask',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
