# Generated by Django 4.2.1 on 2023-06-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_account', '0002_alter_organization_managers_organization_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invite_token',
            field=models.CharField(default='GKU9ZSUXAGV7R0B', max_length=100),
        ),
    ]
