# Generated by Django 4.2.1 on 2023-06-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_account', '0004_alter_organization_invite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='invite_token',
            field=models.CharField(default='3TH22XGLQRCKXC7', max_length=100),
        ),
    ]
