# Generated by Django 4.2.1 on 2023-06-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_account', '0005_alter_organization_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='apollouser',
            name='organizations',
            field=models.ManyToManyField(related_name='organizations', to='apollo_account.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='invite_token',
            field=models.CharField(default='NJOXFYTAD2MYM8R', max_length=100),
        ),
    ]
