# Generated by Django 4.2.1 on 2023-06-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_account', '0006_apollouser_organizations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apollouser',
            name='organizations',
        ),
        migrations.AlterField(
            model_name='organization',
            name='invite_token',
            field=models.CharField(default='MTLBZCRX0AHUGDK', max_length=100),
        ),
    ]
